import re
import json
import datetime
from pathlib import Path

# ITEM 4 (card 4052cdd8): regenerate TRANSLATION_AUDIT.md — machine-generated
# from the live locale files. Mirrors the flatten logic of the CI drift guard
# (src/i18n/__tests__/locales-parity.test.ts) so key counts and emptiness
# checks agree with the gate that actually fails CI.
#
# Repo-root-relative: works in any checkout (no machine-specific paths).
# Run: python3 scripts/gen_translation_audit.py

REPO_ROOT = Path(__file__).resolve().parents[1]
LOCALES_DIR = REPO_ROOT / 'src' / 'i18n' / 'locales'
OUT_PATH = REPO_ROOT / 'src' / 'i18n' / 'TRANSLATION_AUDIT.md'

GUARD = 'src/i18n/__tests__/locales-parity.test.ts'

with open(LOCALES_DIR / 'en.json', encoding='utf-8') as f:
    en = json.load(f)
with open(LOCALES_DIR / 'he.json', encoding='utf-8') as f:
    he = json.load(f)


def flat(obj, prefix=''):
    """Flatten nested dicts AND arrays — arrays become index keys
    (parent.heatmap.dayLabels.0 etc.), exactly like the parity test's
    flatten(), so this audit's key set == the parity test's key set."""
    out = {}
    for k, v in obj.items():
        key = prefix + '.' + k if prefix else k
        if v is not None and isinstance(v, (dict, list)):
            if isinstance(v, dict):
                out.update(flat(v, key))
            else:
                for i, item in enumerate(v):
                    out.update(flat({str(i): item}, f'{key}.{i}'))
        else:
            out[key] = v
    return out


fe, fh = flat(en), flat(he)
missing_he = sorted(set(fe) - set(fh))
missing_en = sorted(set(fh) - set(fe))
empty_he = sorted(k for k, v in fh.items() if not str(v).strip())
empty_en = sorted(k for k, v in fe.items() if not str(v).strip())

ph = re.compile(r'\{\{(\w+)\}\}')
ph_drift = []
for k in fe:
    if k not in fh:
        continue
    a = sorted(ph.findall(str(fe[k])))
    b = sorted(ph.findall(str(fh[k])))
    if a != b:
        ph_drift.append(f'{k}: en={a} he={b}')

clusters = {}
for k in sorted(set(fe) | set(fh)):
    c = '.'.join(k.split('.')[:2])
    clusters.setdefault(c, [0, 0])
    if k in fe:
        clusters[c][0] += 1
    if k in fh:
        clusters[c][1] += 1

lines = []
lines.append('# TRANSLATION AUDIT — en ⇔ he (auto-generated)')
lines.append('')
lines.append('**DO NOT EDIT BY HAND** — regenerate: `python3 scripts/gen_translation_audit.py`')
lines.append(f'**Generated:** {datetime.date.today().isoformat()} · '
             f'en keys: {len(fe)} · he keys: {len(fh)} '
             f'(flatten mirrors {GUARD})')
lines.append('')
status = 'CLEAN' if not (missing_he or missing_en or empty_he or empty_en or ph_drift) else 'DRIFT'
lines.append(f'## Status: {status}')
lines.append('')
lines.append('- missing in he: ' + (str(len(missing_he)) if missing_he else '0'))
lines.append('- missing in en: ' + (str(len(missing_en)) if missing_en else '0'))
lines.append('- empty he values: ' + (str(len(empty_he)) if empty_he else '0'))
lines.append('- empty en values: ' + (str(len(empty_en)) if empty_en else '0'))
lines.append('- placeholder drift: ' + (str(len(ph_drift)) if ph_drift else '0'))
lines.append('')
if missing_he:
    lines.append('### Missing in he.json')
    for k in missing_he:
        lines.append(f'- `{k}`')
    lines.append('')
if missing_en:
    lines.append('### Missing in en.json')
    for k in missing_en:
        lines.append(f'- `{k}`')
    lines.append('')
if ph_drift:
    lines.append('### Placeholder drift')
    for k in ph_drift:
        lines.append(f'- {k}')
    lines.append('')
lines.append('### Cluster coverage (top-level.section — en count / he count)')
for c in sorted(clusters):
    e, h = clusters[c]
    mark = '✅' if e == h else '⚠️'
    lines.append(f'- {mark} `{c}` — {e}/{h}')
lines.append('')
lines.append('**History:** prior audit stale since Aug 1 (regenerated by card 4052cdd8 '
             'item 4); drift that accumulated = the 54 parent-games keys, fixed in PR #219; '
             f'drift guard = {GUARD} (fails CI).')
lines.append('**Scope note:** this file covers key parity only. The old hand-written '
             'audit also recorded hardcoded Hebrew day-label arrays that are still live '
             'in code (src/lib/skillAnalysis.ts getWeeklyData, '
             'src/components/parent/PostcardHub.tsx) — tracked separately on the '
             'AmosBot workboard (owning card pending).')

OUT_PATH.write_text('\n'.join(lines) + '\n', encoding='utf-8')
print('AUDIT regenerated:', status, '| clusters:', len(clusters),
      '| missing:', len(missing_he), '| ph-drift:', len(ph_drift),
      '| keys en/he:', len(fe), '/', len(fh))